# Generated by Django 6.0.8 on 2026-09-03 08:35
#
# `verbose_name`/`help_text`/`Meta.verbose_name(_plural)` below were hand-amended into this
# already-merged, test-only file for the i18n retrofit (fa locale) — inherited from
# dynamic_user's own AbstractDynamicUser, verified via a real `makemigrations --check --dry-run`
# against this app's actual model state. `department` is this app's own field, untouched — out
# of scope, a host's own labeling choice.

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _

import dynamic_user.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, unique=True, verbose_name=_("username")),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name=_("name")),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name=_("email address")),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name=_("phone number"),
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text=_(
                            "Designates whether this user should be treated as active. "
                            "Unselect this instead of deleting accounts."
                        ),
                        verbose_name=_("active"),
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text=_("Designates whether the user can log into this admin site."),
                        verbose_name=_("staff status"),
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name=_("date joined")),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("user"),
                "verbose_name_plural": _("users"),
                "indexes": [
                    models.Index(fields=["email"], name="user_swap_a_email_5f1fe2_idx"),
                    models.Index(fields=["phone"], name="user_swap_a_phone_3cf601_idx"),
                ],
            },
            managers=[
                ("objects", dynamic_user.managers.UserManager()),
            ],
        ),
    ]
