# Generated by Django 6.0.8 on 2026-09-03 08:24
#
# `verbose_name`/`help_text` for the composed dynamic_user mixin fields below were hand-amended
# into this already-merged, test-only file for the i18n retrofit (fa locale) — mirrors the same
# hand-amend done in dynamic_user/migrations/0001_initial.py, verified the same way (a real
# `makemigrations --check --dry-run` against tests.backend.mixin_app.models.Widget's actual
# state, not guessed by hand).

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dynamic_user/avatars/",
                        verbose_name=_("avatar"),
                        help_text=_("Profile picture."),
                    ),
                ),
                (
                    "avatar_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name=_("avatar updated at")
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name=_("created at")),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name=_("updated at")),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text=_("Whether this row is soft-deleted."),
                        verbose_name=_("deleted"),
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name=_("deleted at")),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name=_("email verified")),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name=_("email verified at")
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(default=False, verbose_name=_("phone verified")),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name=_("phone verified at")
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, null=True, verbose_name=_("last seen at")),
                ),
                (
                    "last_seen_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name=_("last seen IP")
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=_("Unstructured host-specific data."),
                        verbose_name=_("metadata"),
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
