# Generated by Django 6.0.8 on 2026-09-03 08:35
#
# `verbose_name`/`help_text`/`Meta.verbose_name(_plural)` below were hand-amended into this
# already-merged, test-only file for the i18n retrofit (fa locale) — inherited from
# dynamic_user's own AbstractProfile/AbstractSetting, verified via a real `makemigrations --check
# --dry-run` against this app's actual model state. `tagline`/`theme` are this app's own fields,
# untouched — out of scope, a host's own labeling choice.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name=_("bio"))),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text=_("Whether this profile is visible to other users."),
                        verbose_name=_("public"),
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=_("user"),
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("profile"),
                "verbose_name_plural": _("profiles"),
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="en", max_length=10, verbose_name=_("language")),
                ),
                (
                    "timezone",
                    models.CharField(default="UTC", max_length=64, verbose_name=_("timezone")),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text=_("Whether this user receives notifications."),
                        verbose_name=_("notifications enabled"),
                    ),
                ),
                ("theme", models.CharField(default="light", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setting",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=_("user"),
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("setting"),
                "verbose_name_plural": _("settings"),
            },
        ),
    ]
