# Generated by Django 6.0.8 on 2026-09-03 08:24
#
# `migrations.swappable_dependency(settings.AUTH_USER_MODEL)` was added to `dependencies` by
# hand after generation — the autodetector omitted it because, under the settings module it ran
# against, AUTH_USER_MODEL resolves to this same migration's own `User` model, which it
# (correctly, for THAT run) treats as an internal, same-migration reference needing no edge.
# But this file ships fixed, for every host: one that swaps AUTH_USER_MODEL to a different app
# entirely (Profile/Setting/AccountDeletionRequest/ChangeLogEntry below all reference
# settings.AUTH_USER_MODEL) needs that other app's User table to exist before this migration
# creates rows with a FK/O2O to it — exactly the precedent django.contrib.admin's own
# `LogEntry` migration sets for the same reason. The two-directions test in
# `docs/CONTRACT.md` §10 item 14 confirms it's safe either way: when AUTH_USER_MODEL still
# resolves to this app's own User (the common case), Django's migration loader drops a
# same-app `__first__` reference as a no-op (`django/db/migrations/loader.py`'s `check_key()`,
# ticket #22325) — it only becomes a real graph edge when the target is genuinely elsewhere.
#
# Deliberately NOT added: an equivalent dependency for this app's OWN
# `DYNAMIC_USER_PROFILE_MODEL`/`DYNAMIC_USER_SETTING_MODEL` settings. Nothing in this file
# references "the resolved profile/setting model" via FK/O2O — `Profile`/`Setting` below ARE
# those models; `options={'swappable': ...}` on their own `CreateModel` operations (already
# present, generated) is the complete, correct mechanism for skipping their table when a host
# swaps them out. Adding a dependency here as well is what produces the CircularDependencyError
# `docs/CONTRACT.md` §10 item 14 documents — a host swapping only Profile/Setting to its own app
# while leaving AUTH_USER_MODEL at this app's default would need that host app to depend on this
# one (via ITS OWN swappable_dependency(AUTH_USER_MODEL) call) while this migration would try to
# depend back on that host app — a two-node cycle. Proven acyclic for real by
# `tests/backend/test_partial_swap.py`.
#
# `verbose_name`/`help_text`/`Meta.verbose_name(_plural)`/`Status` choice labels below were
# hand-amended into this already-merged file, rather than added via a later `0002_alter_*.py`,
# for the i18n retrofit (fa locale) — safe only because no tagged release has shipped yet and no
# real host has migrated against it. Verified via a real `makemigrations --check --dry-run`
# against `models.py`'s actual state (its own diff is what these field kwargs come from), not
# guessed by hand.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _

import dynamic_user.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, unique=True, verbose_name=_("username")),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name=_("name")),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name=_("email address")),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name=_("phone number"),
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text=_(
                            "Designates whether this user should be treated as active. "
                            "Unselect this instead of deleting accounts."
                        ),
                        verbose_name=_("active"),
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text=_("Designates whether the user can log into this admin site."),
                        verbose_name=_("staff status"),
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name=_("date joined")),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("user"),
                "verbose_name_plural": _("users"),
                "swappable": "AUTH_USER_MODEL",
            },
            managers=[
                ("objects", dynamic_user.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="en", max_length=10, verbose_name=_("language")),
                ),
                (
                    "timezone",
                    models.CharField(default="UTC", max_length=64, verbose_name=_("timezone")),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text=_("Whether this user receives notifications."),
                        verbose_name=_("notifications enabled"),
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setting",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=_("user"),
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("setting"),
                "verbose_name_plural": _("settings"),
                "swappable": "DYNAMIC_USER_SETTING_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name=_("bio"))),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text=_("Whether this profile is visible to other users."),
                        verbose_name=_("public"),
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=_("user"),
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("profile"),
                "verbose_name_plural": _("profiles"),
                "swappable": "DYNAMIC_USER_PROFILE_MODEL",
            },
        ),
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", _("Pending")),
                            ("approved", _("Approved")),
                            ("rejected", _("Rejected")),
                            ("finalized", _("Finalized")),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name=_("status"),
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text=_("Optional reason provided by the user."),
                        verbose_name=_("reason"),
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name=_("requested at")),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name=_("reviewed at")),
                ),
                (
                    "finalize_at",
                    models.DateTimeField(blank=True, null=True, verbose_name=_("finalize at")),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=_("reviewed by"),
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=_("user"),
                    ),
                ),
            ],
            options={
                "verbose_name": _("account deletion request"),
                "verbose_name_plural": _("account deletion requests"),
            },
        ),
        migrations.CreateModel(
            name="ChangeLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(verbose_name=_("object id")),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name=_("field name")),
                ),
                ("old_value", models.TextField(blank=True, verbose_name=_("old value"))),
                ("new_value", models.TextField(blank=True, verbose_name=_("new value"))),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name=_("changed at")),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=_("actor"),
                        help_text=_("The user who made this change, if known."),
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name=_("content type"),
                    ),
                ),
            ],
            options={
                "verbose_name": _("change log entry"),
                "verbose_name_plural": _("change log entries"),
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="dynamic_use_email_9aabd7_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="dynamic_use_phone_f71eea_idx"),
        ),
        migrations.AddIndex(
            model_name="accountdeletionrequest",
            index=models.Index(
                fields=["status", "finalize_at"], name="dynamic_use_status_711c79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountdeletionrequest",
            index=models.Index(fields=["user", "status"], name="dynamic_use_user_id_1e91cc_idx"),
        ),
        migrations.AddIndex(
            model_name="changelogentry",
            index=models.Index(
                fields=["content_type", "object_id"], name="dynamic_use_content_a65086_idx"
            ),
        ),
    ]
