# Generated by Django 6.0.8, hand-annotated — v1.1.0's identity change (docs/CONTRACT.md §1).
#
# email: unique=True, null=True/blank=True added — was NOT NULL. phone was already nullable; this
# is what actually changes: a user can now exist with only a phone, only an email, or (unchanged)
# both. username: blank=True added — still NOT NULL at the DB level (a missing username is always
# filled by AbstractDynamicUser.save() before insert, per dynamic_user.usernames); blank=True only
# lets a form/serializer omit it.
#
# The AddConstraint is the floor CLAUDE.md's rule 3 pattern requires for this rule: "at least one
# of email or phone must be provided when creating a user... implemented at the appropriate
# model/business-logic level so it is not possible to bypass the rule simply by using a different
# creation path." AbstractDynamicUser.save() is the readable-error layer; this constraint is what
# makes the rule true even for a caller that bypasses save() entirely (bulk_create, raw SQL
# through the ORM).
#
# No data migration: every row from a pre-1.1.0 install has a non-null email (it was NOT NULL
# until this migration), so the constraint validates clean against existing data with nothing to
# backfill.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("dynamic_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, unique=True, verbose_name="username"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email__isnull", False), ("phone__isnull", False), _connector="OR"
                ),
                name="dynamic_user_user_email_or_phone",
            ),
        ),
    ]
