# Generated by Django 6.0.8 on 2026-09-03 08:35
#
# `verbose_name`/`help_text`/`Meta.verbose_name(_plural)` below were hand-amended into this
# already-merged, test-only file for the i18n retrofit (fa locale) — the values are inherited
# from dynamic_user's own AbstractDynamicUser/AbstractProfile/AbstractSetting, verified via a
# real `makemigrations --check --dry-run` against this app's actual model state (its own diff is
# what these field kwargs come from), not guessed by hand. `department`/`tagline`/`theme` are
# this app's own fields, untouched — out of scope, a host's own labeling choice.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _

import dynamic_user.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, unique=True, verbose_name=_("username")),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name=_("name")),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name=_("email address")),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name=_("phone number"),
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text=_(
                            "Designates whether this user should be treated as active. "
                            "Unselect this instead of deleting accounts."
                        ),
                        verbose_name=_("active"),
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text=_("Designates whether the user can log into this admin site."),
                        verbose_name=_("staff status"),
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name=_("date joined")),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("user"),
                "verbose_name_plural": _("users"),
            },
            managers=[
                ("objects", dynamic_user.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name=_("bio"))),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text=_("Whether this profile is visible to other users."),
                        verbose_name=_("public"),
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=_("user"),
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("profile"),
                "verbose_name_plural": _("profiles"),
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="en", max_length=10, verbose_name=_("language")),
                ),
                (
                    "timezone",
                    models.CharField(default="UTC", max_length=64, verbose_name=_("timezone")),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text=_("Whether this user receives notifications."),
                        verbose_name=_("notifications enabled"),
                    ),
                ),
                ("theme", models.CharField(default="light", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setting",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=_("user"),
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": _("setting"),
                "verbose_name_plural": _("settings"),
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="swapped_app_email_15b479_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="swapped_app_phone_93425a_idx"),
        ),
    ]
